version: "3.9"

services:
  web:
    build: .
    command: gunicorn Journal.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: changeme-in-development
      DATABASE_URL: postgres://journal:journal@db:5432/journal
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: journal
      POSTGRES_USER: journal
      POSTGRES_PASSWORD: journal
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
